version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "06:00" }
    open-pull-requests-limit: 1
    groups:
      tooling:
        patterns: ["eslint*", "prettier*", "vitest*", "playwright*", "zx", "dependency-cruiser", "madge", "knip"]
      supabase:
        patterns: ["supabase", "@supabase/*"]
    # optional: ignore majors to avoid churn
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
