name: Dependabot auto-merge
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write
  contents: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta
      - name: Enable auto-merge for patch/minor
        if: contains('patch,minor', steps.meta.outputs.update-type)
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
